services:
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front_end
    depends_on:
      - custom_app
  custom_app:
    build: .
    restart: always
    networks:
      - front_end
      - back_end
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    volumes:
      - mongo_db-data:/data
    #Variables para definir usuario y pass de base de datos
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - back_end
volumes:
  mongo_db-data:
networks:
  front_end:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.10.0.0/16
  back_end:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 193.10.0.0/16